services:
  - type: web
    name: campconnect-whatsapp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn whatsapp_bot:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: WHATSAPP_PHONE_ID
        sync: false
      - key: WHATSAPP_TOKEN
        sync: false
      - key: WEBHOOK_VERIFY_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: HF_TOKEN
        sync: false

  - type: web
    name: campconnect-ui
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run campconnect.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: GROQ_API_KEY
        sync: false
      - key: HF_TOKEN
        sync: false
